---
title: "He’eia Model - Stream PFR"
author: "Nakoa Farrant"
date: "5/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(deSolve)
library(ggplot2)
library(schoolmath)
library(tidyverse)
library(TropFishR)
require(MASS)
require(dplyr)
```

```{r}
# The below values are characteristic of Mugil cephalus (striped mullet, ‘ama‘ama) as defined in the S.I. of Cheung, et al. 2013, who derived these values from data that is freely available at fishbase.org
Linf_mugil = 100 # asymptotic length for Mugil cephalus, [cm]
K_mugil = 0.27 # von Bertalanffy growth parameter, [1/year]
a_mugil = 0.0085 # length-weight conversion parameter from FishBase
b_mugil = 3.0 # length-weight conversion parameter from FishBase
Winf_mugil = a_mugil*Linf_mugil^b_mugil # asymptotic weight using length-weight conversion [grams]

# For Mugil cephalus (striped mullet), natural mortality can be empirically derived using the method developed by Then, et al. 2015
M_mugil = M_empirical(Linf = Linf_mugil, K_l = K_mugil, method = "Then_growth") # [1/year]
```


# 6-Hour Time Step: Model Equations
Realized that running into issues with the stream and tide specifications that are determined based on the value of t and need to be adjusted based on the time step being taken
```{r}

fish_func6 <- function(t, state6, pars6) {
  with(as.list(c(state6, pars6)), {

    # define physical parameters of ecosystem 
    h_st = 0.5 # average depth of stream [m]
    l_st = 700 # length of interest for He‘eia Stream [m]
    w_st = 15 # approximate width of stream [m]
    
    A_fp = 360000 # area of fishpond [m^2]
    h_fp = 0.4 # average depth of fishpond water column [m]
    
    A_sed = 360000 # area of sediment below fishpond water column [m^2]
    h_sed = 0.005 # depth of sediment of interest in meters [m]
    
    # define volumes of compartments - m^3
    V_st = h_st*l_st*w_st # stream
    V_fp = A_fp*h_fp # fishpond water
    V_sed = A_sed*h_sed # fishpond sediment
    
    # create an integer counter variable, time is otherwise in 6 hr intervals
    step = t*365*4 
    
    # temperature in ºC
    T_max = 35.2 # maximum in the summer
    T_min = 20.5 # minimum in the winter
    T1 = (T_max - T_min)/2 * (sin(2*pi*step - pi/2) + 1) + T_min
    
    #k_fd = (0.0256 + 0.0123*T1)/4 # temperature-driven fish mortality rate [1/6hr]
    
    # define flow terms- m^/d
    Q_st = 3500 # average He‘eia stream flow conditions
    
    # There are 4 tidal cycles every day that alternate between flood and ebb tides at each 6 hour time     step. Additionally, roughly every 8 days there is a switch from spring tide to neap tide based on       the moon cycle (spring when full or new moon, neap during quarter moon phases). This results in         desired shifts from spring to neap every ~32 tide shifts (8 days * 4 tides/day)
    
    # Every lunar cycle (approximately a month), there are two sets of spring and two sets of neap tides     # which totals to 128 tidal cycles. By using the modulo operator based on 128 tidal cycles, you can     # get all of the spring and neap cycles and all of the flood and ebb cycles in each month which will     # repeat each month.
    if (step %% 128 < 32){
      # arbitrarily start with the first 32 spring tide cycles
      if (as.integer(step) %% 2 == 0){
        # alternate between spring flood and spring ebb based on being an even or odd step
        Q_tide = sp_fl
      }
      else{
        Q_tide = sp_ebb
      }
    }
    else if (step %% 128 > 31 & step %% 128 < 64){
      # shift to  32 neap tides
      if(as.integer(step) %% 2 == 0){
        # alternate between neap flood and neap ebb based on being an even or odd step
        Q_tide = np_fl
      }
      else{
        Q_tide = np_ebb
      }
    }
    else if (step %% 128 > 63 & step %% 128 < 96){
      # shift back to spring tides
      if(as.integer(step) %% 2 == 0){
        # alternate between spring flood and spring ebb based on being an even or odd step
        Q_tide = sp_fl
      }
      else{
        Q_tide = sp_ebb
      }
    }
    else{
      # shift back to neap tides
      if(as.integer(step) %% 2 == 0){
        # alternate between neap flood and neap ebb based on being an even or odd step
        Q_tide = np_fl
      }
      else{
        Q_tide = np_ebb
      }
    }
    
     
    # Specify temporal variability in He'eia stream flow rate based on mean
    # measurements from July 2014-July 2015
    # m^3 / 6 hours
    if (step %% 365 < 10) {
        # End of July 2014
        Q_st = 8860/4
    }
    else if (step %% 365 > 9 && step %% 365 < 40) 
    {
        # Aug 2014
        Q_st = 4620/4
    }
    else if (step %% 365 > 39 && step %% 365 < 68) 
    {
        # Sept 2014
        Q_st = 4650/4
    }
    else if (step %% 365 > 67 && step %% 365 < 99) 
    {
        # Oct 2014
        Q_st = 6560/4 
    }
    else if (step %% 365 > 98 && step %% 365 > 129) 
    { 
        # Nov 2014
        Q_st = 4970/4 
    }
    else if (step %% 365 > 128 && step %% 365 < 160) 
    {
       # Dec 2014 
       Q_st = 4580/4
    }
    else if (step %% 365 > 159 && step %% 365 < 191) 
    {
       # Jan 2015 
       Q_st = 4130/4 
    }
    else if (step %% 365 > 190 && step %% 365 < 219) 
    { 
       # Feb 2015 
       Q_st = 3990/4 
   }
    else if (step %% 365 > 218 && step %% 365 < 250) 
    {
       # March 2015 
       Q_st = 3940/4 
    }
    else if (step %% 365 > 249 && step %% 365 < 280) 
    {
       # April 2015
       Q_st =  3840/4 
    }
    else if (step %% 365 > 279 && step %% 365 < 312) 
    {
       # May 2015
       Q_st =  3600/4
    }
    else if (step %% 365 > 311 && step %% 365 < 342) 
    {
       # June 2015
       Q_st =  4160/4
    } 
    else if (step %% 365 > 341 && step %% 365 < 366) 
    {
      # remainder of July 2015
       Q_st = 3770/4 
    }
    else {
       Q_st = 3500/4 # average stream flow during this period
    }

    
    W_No_taro = 0.148*Q_st # loading of organic N runoff from taro agriculture [g/6hr]
    W_Na_taro = 0.006*Q_st # loading of ammonia N runoff from taro agriculture [g/6h]
    W_Ni_taro = 0.006*Q_st # loading of nitrate N runoff from taro agriculture [g/6h]

  # Stream organic N
  dNo_st <- (W_No_taro- Q_st*No_st+(-k_oa*No_st + k_ao*Na_st)*V_st)/V_st
  # Stream ammonium
  dNa_st <- (W_Na_taro - Q_st*Na_st+(k_oa*No_st-(k_ao+k_nit+k_av)*Na_st + k_nit_red*Ni_st)*V_st)/V_st
  # Stream nitrate    
  dNi_st <- (W_Ni_taro- Q_st*Ni_st + (k_nit*Na_st-k_nit_red*Ni_st)*V_st)/V_st
  # Fishpond water organic N
  dNo_fp <- ((Q_st*No_st+((-k_oa-k_s)*No_fp+k_ao*Na_fp+k_r*No_sd)*V_fp + Q_tide*(No_ocean-No_fp)))/V_fp
  # Fishpond water ammonium    
  dNa_fp <- (Q_st*Na_st + (k_oa*No_fp - (k_ao+k_nit+k_av+k_s)*Na_fp + k_r*Na_sd)*V_fp+Q_tide*
             (Na_ocean-Na_fp)-((r_NChl*k_g20*((Na_fp+Ni_fp)/(k_SN+No_fp+Ni_fp))+r_NChl*k_ra)*alg))/V_fp
  # Fishpond water nitrate    
  dNi_fp <- (Q_st*Ni_st + (k_nit*Na_fp-k_s*Ni_fp+k_r*Ni_sd)*V_fp + Q_tide*(Ni_ocean-Ni_fp)-
             ((r_NChl*k_g20*((Na_fp+Ni_fp)/(k_SN+Na_fp+Ni_fp)) + r_NChl*k_ra)*alg))/V_fp
  # Sediment organic N    
  dNo_sd <- ((k_s*No_fp-(k_oa+k_b+k_r)*No_sd + k_ao*Na_sd)*V_sed)/V_sed
  # Sediment ammonium
  dNa_sd <- ((k_s*Na_fp + k_oa*No_sd-(k_ao+k_nit_sed+k_r+k_b)*Na_sd + k_nit_red*Ni_sd)*V_sed)/V_sed
  # Sediment nitrate    
  dNi_sd <- ((k_s*Ni_fp+k_nit_sed*Na_sd-(k_denit+k_nit_red+k_r+ k_b)*Ni_sd)*V_sed)/V_sed
  # Algae density
  dalg <- (((r_NChl*k_g20*((Na_fp+Ni_fp)/(k_SN+Na_fp+Ni_fp)) -k_ra -((Q_st-Q_tide)/V_fp)))*
           alg -k_ac*fish*alg)
  # Fish density
  dfish <- (k_fg*alg - k_fd)*fish # question the parentheses location from a units perspective

  return(list(c(No_st = dNo_st, Na_st = dNa_st, Ni_st = dNi_st, No_fp = dNo_fp, Na_fp = dNa_fp, Ni_fp = dNi_fp, No_sd = dNo_sd, Na_sd = dNa_sd, Ni_sd = dNi_sd, alg = dalg, fish = dfish)))
  
})
}
```

# Model Specification
```{r}
years = 100
t6 <- seq(0, years, by = 1/365/4) # 100 years with a 6 hour time step

# For reference, TSS export from Kako'o marshland 2013 to 2017 was 18.5 mg/L

pars6 <- c(
      k_oa = 0.01/4, # conversion of organic N to ammonium N [1/6hr]
      k_ao = 0.1/4, # conversion of ammonium N to organic N [1/6hr]
      k_nit = 0.5/4, # nitrification in water column [1/6hr]
      k_nit_red = 0.1/4, # reduction of nitrate N to ammonium N [1/6hr]
      k_av = 0.7/4, # ammonium to ammonia volatilization rate [1/6hr]
      k_nit_sed = 0.05/4, # nitrification rate in the sediment [1/6hr]
      k_denit = 0.01/4, # denitrification rate constant [1/6hr]
      
      # Fishpond water-sediment exchange rate constants
      k_r = 0.1/4, # resuspension rate [1/6hr]
      k_s = 0.8/4, # settling rate [1/6hr], used to be 0.05 1/day. If going to make it this high, maybe it should just be related to phytoplankton settling rate due to their size. This is from Burdoff and Lorenzen
      k_b = 0.001/4, # burial removal rate [1/6hr] 
      
      # fish and algae rates and constants
      r_NChl = 0.2, # ratio of nitrogen to Chla in algae [g N/g Chla]
      k_ra = 0.025/4, # algae respiration rate [1/6hr]
      k_SN = 0.015, # half-saturation constant for N uptake [gN/m^3], Chapra says 10-15 mgN/m^3. Previously had this at 150 mg/m^3
      k_g20 = 1.5/4, # algae growth rate constant at 20 degrees C [1/6hr]
      #k_fg = 0.015/4, # rate of fish growth due to algae consumption [1/6hr]
      # K for mullet is 0.27 1/yr -> 0.0007 1/day, this is lower than the current growth rate but the current growth rate also seems particularly low
      k_ac = 0.0012/4, # rate of algae consumption by fish [1/6hr]
      k_fg = 0.15/4, # rate of fish growth based on VBGF K [1/6hr]
      k_fd = M_mugil/365/4, # rate of fish death from empirical Then formula [1/6hr]
      
      # nitrogen concentrations in ocean - units g/m^3
      No_ocean = 0.001,
      Na_ocean = 0.04, 
      Ni_ocean = 0.02,
      
      # water volume flux rate (m^3/6hr)
      sp_fl= 191660/4,
      sp_ebb = -174880/4,
      np_fl = 141384/4,
      np_ebb = -159938/4
      
)

# there will be seasonal variability in the baseline nitrogen forms present in the stream, fishpond and sediment based on tides, timing of nitrogen applications to the lo‘i, precipitation

# specify initial concentrations of nitrogen forms (g/m^3) and for algae and fish (g/m^2)

# Information on nitrogen output from Kako‘o taro agriculture from Bremer, et al 2018: total N is 0.16 
# (+/- 0.08) g/m^3 with nitrate N 0.006 (+/- 0.014) g/m^3 and ammonia N at 0.006 (+/- 0.006) g/m^3
# these represent an order of magnitude smaller ammonia and nitrate N composition from before

# Nitrogen in FP water column (no measures of organic N):
# summer mean:
# nitrate = 0.66 g/m^3
# ammonium = 0.02 g/m^3

# winter mean:
# nitrate = 0.69 g/m^3
# ammonium = 0.05 g/m^3

# low measured levels of nitrite (0.01 and 0.02 g/^3 in winter and summer, respectively)

# Sediment nitrogen concentrations based on the Briggs, et al paper from 2013 on coastal endmembers

# conversion factor for NH4-N: 1 mg NH4/l = 55.4 umol NH4/l

# In the first 1cm of sediment:
# ammonium (in terrogenous near egret island): 0.54 g/m^3 (~30 uM)
# ammonium (in carbonate sediment in more central part of pond): 0.63 g/m^3 (~35 uM)

# 0.59 g/m^3 average

# organic N: 

# waiting on organic N in FP and sediment, nitrate in sediment.


state6 <- c(
           No_st = 0.148, # stream initial organic N [g/m^3]
           Na_st = 0.006, # stream initial ammonium [g/m^3]
           Ni_st = 0.006, # stream initial nitrate [g/m^3]
           No_fp = 0.1, # fishpond initial organic N [g/m^3], estimated from Charles Young thesis
           Na_fp = 0.035, # fishpond initial ammonium [g/m^3]
           Ni_fp = 0.675, # fishpond initial nitrate [g/m^3]
           No_sd = 0.1, # fishpond sediment initial organic N [g/m^3], estimated from Young thesis
           Na_sd = 0.6, # fishpond sediment initial ammonium [g/m^3], sediment is a source for ammonium according to Hargreaves (1998)
           Ni_sd = 0.01, # fishpond sediment initial nitrate [g/m^3], sediment is a sink for nitrate according to Hargreaves (1998). Same as original model
           alg = 0.0015,    # initial algae [g Chl/m^3]
           fish = 8) # initial fish density [g/m^3] 1150000 g/144000m^3 = 7.986 g/m^3

# According to Mohlenkamp et al. 2019, from 2006-2009, Paepae o He'eia produced ~1.2 metric tons of moi (Pacific Threadfin) 

# historical estimates for this fishpond max out around 15 metric tons (15,000 kg) with an asymptotic weight of 8.5 kg per striped mullet this would amount to ~1750 fully grown striped mullet.
# According to FishBase, the common length is 50 cm which equates to a weight closer to 1 kg based on the length-weight conversion factor.  This would require closer to 15,000 fish to reach capacity

# hypothetically stock with 3 cm fingerlings that have a mass of ~230 grams each based on length-weight conversion. These fish would be an estimated 1.5 years old based on the VBGF curve and the estimated weight. If we stock the fishpond with 5,000 fingerlings, the inital mass in the fishpond is 1.15*10^6 grams (1.1 metric tons).

# fish base indicates sexual maturity at 3-4 years for Mugil cephalus. At the end of 4 years, fish are estimated to be ~3.2 kg each, which would translate to 15 metric tons

# Biswas, et al. 2012 (https://www.sciencedirect.com/science/article/pii/S0044848612000658) suggests a stocking density of M. cephalus fry (~0.17 g in size) at 15,000 fry/hectar. He'eia fishpond is 36 ha. This is 91,800 grams of M. cephalus stocked in the fishpond, which is close to what was suggested above with slighly larger fish

```


```{r}
fp6_out <- ode(y = state6, times = t6, func = fish_func6, parms = pars6, method = "euler")
# the method used to solve the ODE matters for the results
```

```{r}
plot(fp6_out)
```

```{r}
fp_df6 <- as.data.frame(fp6_out)
```

```{r}
# Make a nice ggplot with desired content
fp_water6 <- fp_df6 %>% 
  dplyr::select(time, No_fp, Na_fp, Ni_fp) %>% 
  gather('No_fp', 'Na_fp', 'Ni_fp', key = "nitrogen", value = "concentration")

n_fp6_plot <- ggplot(data = fp_water6, aes(x = time, y = concentration, col=nitrogen)) +
  geom_line() +
  guides(fill=FALSE) +
  labs(title = "Modeled Nitrogen Compounds in He'eia Fishpond Water Column\n Time Step = 6 h", x = "Time (Years)", y = "Concentration (mg/L)") +
  theme(axis.text.x= element_text(size = 8, hjust = .2), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust = 0.5)) +
  scale_colour_hue(name="Nitrogen Types",
                         breaks=c("Na_fp", "Ni_fp", "No_fp"),
                        labels = c(as.expression(bquote(NH[4]^-1-N)), 
         as.expression(bquote(NO[3]^-1-N)), 
         "Organic N"))

n_fp6_plot
```


```{r, message=FALSE}
# Read in water quality data from 2014-2015 in He'eia Fishpond CSV
heeia_data = read_csv('heeia_wq_data_2014_2015.csv') %>% 
  arrange(date) %>% 
  dplyr::select(date:turbidity)

```


```{r}
nitrate_data <- heeia_data %>% 
  dplyr::select(date, statistic, nitrate) %>% 
  filter(statistic == "Mean" | statistic == "Stdv" | statistic == "N") %>% 
  spread(key = statistic, value = "nitrate") %>% 
  rename(nit_mean = Mean, nit_sd = Stdv) %>% 
  mutate(nit_se = nit_sd / sqrt(N)) %>% 
  mutate(day_ct = 0) %>% 
  na.omit()

  for (i in 3:length(nitrate_data$day_ct)){
    nitrate_data$day_ct[i-1] = nitrate_data$day_ct[i-2] + as.integer(nitrate_data$date[i]-nitrate_data$date[i-1])
  }

ammonium_data <- heeia_data %>% 
  dplyr::select(date, statistic, ammonia) %>% 
  filter(statistic == "Mean" | statistic == "Stdv" | statistic == "N") %>% 
  spread(key = statistic, value = "ammonia") %>% 
  rename(amm_mean = Mean, amm_sd = Stdv) %>% 
  mutate(amm_se = amm_sd / sqrt(N)) %>% 
  mutate(day_ct = 0) %>% 
  na.omit() %>% 
  filter(amm_mean != max(amm_mean)) # removed an outlier, could be related to a storm event. Could remove this line to add

  for (i in 3:length(ammonium_data$day_ct)){
    ammonium_data$day_ct[i-1] = ammonium_data$day_ct[i-2] + as.integer(ammonium_data$date[i]-ammonium_data$date[i-1])
  }
```



```{r}
nitrate_data_plot <- ggplot(data = nitrate_data, aes(x = date, y = nit_mean)) +
  geom_point(col = 'blue') +
  geom_errorbar(aes(ymin=nit_mean-nit_se, ymax=nit_mean+nit_se), width=.1, col = 'blue') +
  geom_line(linetype = "dashed", col = 'blue') +
  labs(title='Nitrate Concentrations in He‘eia Fishpond 2014-2015', x = 'Sampling Date', y = 'Concentration (mg/L)') +
  guides(fill = FALSE) +
  theme(axis.text.x= element_text(size = 8), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust = 0.5)) 

nitrate_data_plot
```

```{r}

ammonia_data_plot <- ggplot(data = ammonium_data, aes(x = date, y = amm_mean)) +
  geom_point(col = 'magenta') +
  geom_errorbar(aes(ymin=amm_mean-amm_se, ymax=amm_mean+amm_se), width=.1, col = 'magenta') +
  geom_line(linetype = "dashed", col = 'magenta') +
  labs(title='Ammonium Concentrations in He‘eia Fishpond 2014-2015', x = 'Sampling Date', y = 'Concentration (mg/L)') +
  guides(fill=FALSE) +
  theme(axis.text.x= element_text(size = 8), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust = 0.5))

ammonia_data_plot
```

```{r}
fp_nitrate6 <- fp_water6 %>% 
  filter(nitrogen == "Ni_fp")

fp_ammonium6 <- fp_water6 %>% 
  filter(nitrogen == "Na_fp")
```

```{r}
# try to compare first year of modeled fishpond nitrate to the 2014-2015 fishpond water nitrate data
fp_nitrate_y1 <- fp_water6 %>% filter(nitrogen == "Ni_fp") %>% 
  filter(time >= 0 & time < 1)


nitate_combo_y1 = ggplot(data = fp_nitrate_y1, aes(x = time, y = concentration)) +geom_line(col = 'green') + geom_point(data = nitrate_data, aes(x = day_ct/365, y = nit_mean),colour='blue')

nitate_combo_y1
```

```{r}
# compare to year 80 of modeled fishpond nitrate to the 2014-2015 fishpond water nitrate data
fp_nitrate_y45 <- fp_water6 %>% filter(nitrogen == "Ni_fp") %>% 
  filter(time >= 45 & time < 46)


nitate_combo_y45 = ggplot(data = fp_nitrate_y45, aes(x = time, y = concentration)) +geom_line(col = 'green') + geom_point(data = nitrate_data, aes(x = day_ct/365+45, y = nit_mean),colour='blue')

nitate_combo_y45
```

```{r}
# compare to year 1 of modeled fishpond ammonium N to the 2014-2015 fishpond water ammonium data
fp_amm_y1 <- fp_water6 %>% filter(nitrogen == "Na_fp") %>% 
  filter(time >= 0 & time < 1)


amm_combo_y1 = ggplot(data = fp_amm_y1, aes(x = time, y = concentration)) +geom_line(col = 'red') + geom_point(data = ammonium_data, aes(x = day_ct/365, y = amm_mean),colour='magenta')

amm_combo_y1
```


```{r}
# compare to year 80 of modeled fishpond ammonium N to the 2014-2015 fishpond water ammonium data
fp_amm_y45 <- fp_water6 %>% filter(nitrogen == "Na_fp") %>% 
  filter(time >= 45 & time < 46)


amm_combo_y45 = ggplot(data = fp_amm_y45, aes(x = time, y = concentration)) +geom_line(col = 'red') + geom_point(data = ammonium_data, aes(x = day_ct/365+45, y = amm_mean),colour='magenta')

amm_combo_y45
```

```{r}
# need to average 4 times steps to get the average for that day. Assign a day number in integer form that can be compared against the days where there is data. Then make calculate MSE or some other metric for comparison

# create daily averages for nitrate concentrations modeled in the fishpond water
fp_nit_day <- data.frame(day = seq(1,365*years),
                         concentration = 0)

for (i in 1:length(fp_nit_day$day)){
  fp_nit_day$concentration[i] =  (fp_nitrate6$concentration[i]+fp_nitrate6$concentration[i+1]+ fp_nitrate6$concentration[i+2]+fp_nitrate6$concentration[i+3])/4
}

# create daily averages for ammonium concentrations modeled in the fishpond water
fp_amm_day <- data.frame(day = seq(1,365*years),
                         concentration = 0)

for (i in 1:length(fp_amm_day$day)){
  fp_amm_day$concentration[i] =  (fp_ammonium6$concentration[i]+fp_ammonium6$concentration[i+1]+ fp_ammonium6$concentration[i+2]+fp_ammonium6$concentration[i+3])/4
}

# for days outside of the data range of the first year, need to do some kind of offset (subtract 365*# of years different from the first year)

```



