---
title: 'He’eia Model: Main Markdown'
author: "Nakoa Farrant"
date: "4/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(deSolve)
library(tidyverse)
library(ggplot2)
```

# Model Equations
```{r}
fish_function <- function(t, state, pars) {
  with(as.list(c(state, pars)), {

    # define physical parameters of ecosystem 
    h_st = 0.5 # average depth of stream [m]
    l_st = 700 # length of interest for He‘eia Stream [m]
    w_st = 15 # approximate width of stream [m]
    
    A_fp = 360000 # approximate area of fishpond [m^2]
    h_fp = 0.4 # average depth of fishpond water column [m]
    
    A_sed = 360000 # approximate area of sediment [m^2]
    h_sed = 0.005 # depth of sediment of interest in meters [m]
    
    # define volumes of compartments - m^3
    V_st = h_st*l_st*w_st # stream
    V_fp = A_fp*h_fp # fishpond water
    V_sed = A_sed*h_sed # fishpond sediment
    
    # temperature in ºC
    T_max = 35.2 # maximum in the summer
    T_min = 20.5 # minimum in the wither
    T1 = (T_max - T_min)/2 * (sin(2*pi*t - pi/2) + 1) + T_min
    
    k_fd = 0.0256 + 0.0123*T1 # fish mortality rate [1/d]
    
    # define flow terms - m^3/day
    Q_st = 3500 # mean flow rate of stream as measured in Charles Young Thesis
    # this was measured to be fairly consistent throughout all tides. This
    # is the rate of stream flow among the mangrove bushes by Kako'o and Kamehameha Highway.

    # Spring Flood Tide -> 896,000 m^3/d, spring Ebb Tide -> -904,000 m^3/d
    # Neap Flood Tide -> 536,000 m^3/d, Neap Ebb Tide -> -482,000 m^3/d
    E_tide_spring = -8300 # difference between spring flood and spring ebb tide m^3/d 
    E_tide_neap = 54000 # difference between neap flood and neap ebb tide m^3/d

    daily_tide_diff = (E_tide_neap - E_tide_spring)/8
    
    if (t < 4){
      Q_tide = E_tide_neap - t*daily_tide_diff
    }
    else{
      if (((t-4) %% 16) == 0){
        Q_tide = E_tide_spring
      }
        else if (((t-4) %% 16) > 0 && ((t-4) %% 16) < 8)
        {
          Q_tide = E_tide_spring + ((t-4) %% 16)*daily_tide_diff
        }
        else if (((t-4) %% 16) == 8)
        {
             Q_tide = E_tide_neap
        }
        else if (((t-4) %% 16) > 8 && ((t-4) %% 16) <= 16)
        {
          Q_tide = E_tide_neap - (((t-4)%%16)-8)*daily_tide_diff
        }
      }
        
     

    # Specify temporal variability in He'eia stream flow rate based on mean
    # measurements from 1943-2018
    if (t < 68) 
      {
      # End of July, Aug, and Sept
        Q_st = 4160 # m^3/day
    } 
    else if (t > 67 && t < 99) 
    {
        # Oct
        Q_st = 4890 # m^3/day 
    }
    else if (t > 98 && t > 129) 
    {
      # Nov
        Q_st = 6850 # m^3/day
    }
    else if (t > 128 && t < 160)
    {
      # Dec
       Q_st = 6600 # m^3/day
    }
   else if (t > 159 && t < 191) 
   {
     # Jan
       Q_st = 6360 # m^3/day
   }
    else if (t > 190 && t < 219) 
    {
      # Feb
       Q_st = 6360 # m^3/day
    }
    else if (t > 218 && t < 250) 
    {
      # March
       Q_st = 8070 # m^3/day
    }
    else if (t > 249 && t < 280) 
    {
      # April
       Q_st =  6120 # m^3/day
    }
    else if (t > 279 && t < 312) 
    {
      # May
       Q_st =  5630 # m^3/day
    }
    else if (t > 311 && t < 342) 
    {
      # June
       Q_st =  3670 # m^3/day 
    }  
    else if (t > 341) 
    {
      # remainder of July
      Q_st = 4160 # m^3/day
    }
    # Specify temporal variability in He'eia stream flow rate based on mean
    # measurements from July 2014-July 2015
    if (t < 10) 
    {
        # End of July 2014
        Q_st = 8860 # m^3/day
    }
    else if (t > 9 && t < 40) 
    {
        # Aug 2014
        Q_st = 4620 # m^3/day
    }
    else if (t > 39 && t < 68) 
    {
        # Sept 2014
        Q_st = 4650 # m^3/day
    }
    else if (t > 67 && t < 99) 
    {
        # Oct 2014
        Q_st = 6560 # m^3/day
    }
    else if (t > 98 && t > 129) 
    { 
        # Nov 2014
        Q_st = 4970 # m^3/day
    }
    else if (t > 128 && t < 160) 
    {
       # Dec 2014 
       Q_st = 4580 # m^3/day
    }
    else if (t > 159 && t < 191) 
    {
       # Jan 2015 
       Q_st = 4130 # m^3/day
    }
    else if (t > 190 && t < 219) 
    { 
       # Feb 2015 
       Q_st = 3990 # m^3/day
   }
    else if (t > 218 && t < 250) 
    {
       # March 2015 
       Q_st = 3940 # m^3/day
    }
    else if (t > 249 && t < 280) 
    {
       # April 2015
       Q_st =  3840 # m^3/day
    }
    else if (t > 279 && t < 312) 
    {
       # May 2015
       Q_st =  3600 # m^3/day
    }
    else if (t > 311 && t < 342) 
    {
       # June 2015
       Q_st =  4160 # m^3/day
    } 
    else if (t > 341) 
    {
      # remainder of July 2015
       Q_st = 3770 # m^3/day
    }
       # Stream organic N
  dNo_st <- (No_st - Q_st*No_st+(-k_oa*No_st + k_ao*Na_st)*V_st)/V_st
  # Stream ammonium
  dNa_st <- (Na_st - Q_st*Na_st+(k_oa*No_st-(k_ao+k_nit+k_av)*Na_st + k_nit_red*Ni_st)*V_st)/V_st
  # Stream nitrate    
  dNi_st <- (Ni_st - Q_st*Ni_st + (k_nit*Na_st-k_nit_red*Ni_st)*V_st)/V_st
  # Fishpond water organic N
  dNo_fp <- ((Q_st*No_st+((-k_oa-k_s)*No_fp+k_ao*Na_fp+k_r*No_sd)*V_fp + Q_tide*(C_No_ocean-No_fp)))/V_fp
  # Fishpond water ammonium    
  dNa_fp <- (Q_st*Na_st + (k_oa*No_fp - (k_ao+k_nit+k_av+k_s)*Na_fp + k_r*Na_sd)*V_fp+Q_tide*
             (C_Na_ocean-Na_fp)-((a_Na*k_g20*((Na_fp+Ni_fp)/(k_SN+No_fp+Ni_fp))+a_Na*k_ra)*alg))/V_fp
  # Fishpond water nitrate    
  dNi_fp <- (Q_st*Ni_st + (k_nit*Na_fp-k_s*Ni_fp+k_r*Ni_sd)*V_fp + Q_tide*(C_Ni_ocean-Ni_fp)-
             ((a_Na*k_g20*((Na_fp+Ni_fp)/(k_SN+Na_fp+Ni_fp)) + a_Na*k_ra)*alg))/V_fp
  # Sediment organic N    
  dNo_sd <- ((k_s*No_fp-(k_oa+k_b+k_r)*No_sd + k_ao*Na_sd)*V_sed)/V_sed
  # Sediment ammonium
  dNa_sd <- ((k_s*Na_fp + k_oa*No_sd-(k_ao+k_nit_sed+k_r+k_b)*Na_sd + k_nit_red*Ni_sd)*V_sed)/V_sed
  # Sediment nitrate    
  dNi_sd <- ((k_s*Ni_fp+k_nit_sed*Na_sd-(k_denit+k_nit_red+k_r+ k_b)*Ni_sd)*V_sed)/V_sed
  # Algae density
  dalg <- (((a_Na*k_g20*((Na_fp+Ni_fp)/(k_SN+Na_fp+Ni_fp))-k_ra -((Q_st-Q_tide)/V_fp)))*
           alg*(1-alg/K_alg)-k_ac*fish*alg)
      
  # Fish density
      
  # When algae density drops below a critical level, fish growth declines and fish begin to die off 
  # until algae density increases again in response to predator decline
  if (alg < 500) 
  {
    dfish <- -k_fd*fish
  }
  else 
  {
    dfish <- (k_fg*alg-k_fd)*fish
  }
  
  return(list(c(No_st = dNo_st, Na_st = dNa_st, Ni_st = dNi_st, No_fp = dNo_fp, Na_fp = dNa_fp, Ni_fp = dNi_fp, No_sd = dNo_sd, Na_sd = dNa_sd, Ni_sd = dNi_sd, alg = dalg, fish = dfish)))

})
}
```

# Model Specification
```{r}

t <- seq(0, 10, by = 1/365) # spinning up over 100 years with a daily time step

# TSS export from Kako'o marshland 2013 to 2017 was 18.5 mg/L

pars <- c(
      k_oa = 0.01, # conversion of organic N to ammonium N [1/day]
      k_ao = 0.1, # conversion of ammonium N to organic N [1/day]
      k_nit = 0.5, # nitrification in water column [1/day]
      k_nit_red = 0.1, # reduction of nitrate N to ammonium N [1/day]
      k_av = 0.7, # ammonium to ammonia volatilization rate [1/day]
      k_nit_sed = 0.05, # nitrification rate in the sediment [1/day]
      k_denit = 0.01, # denitrification rate constant [1/day]
      
      # Fishpond water-sediment exchange rate constants
      k_r = 0.1, # resuspension rate [1/d]
      k_s = 0.05, # settling rate [1/d]
      k_b = 0.001, # burial removal rate [1/d] 
      
      # fish and algae rates and constants
      a_Na = 0.2, # ratio of nitrogen to Chla in algae [g N/g Chla]
      k_ra = 0.025, # algae respiration rate [1/d]
      k_SN = 0.15, # half-saturation constant for N uptake [gN/m^3]
      k_g20 = 1.5, # algae growth rate constant at 20 degrees C [1/d]
      k_fg = 0.015, # rate of fish growth due to algae consumption [1/d]
      k_ac = 0.0012, # rate of algae consumption by fish [1/d]
      K_alg = 5000, # carrying capacity of algae [g/m^3]
      
      # nitrogen concentrations in ocean - units g/m^3
      C_No_ocean = 0.001,
      C_Na_ocean = 0.04, 
      C_Ni_ocean = 0.02,
      
      No_in_taro = 0.148*3600, # loading of organic N runoff from taro agriculture [g/day]
      Na_in_taro = 0.006*3600, # loading of ammonia N runoff from taro agriculture [g/day]
      Ni_in_taro = 0.006*3600 # loading of nitrate N runoff from taro agriculture [g/day])
)

# there will be seasonal variability in the baseline nitrogen forms present in the stream, fishpond and sediment based on tides, timing of nitrogen applications to the lo‘i, precipitation

# specify initial concentrations of nitrogen forms (g/m^3) and for algae and fish (g/m^2)

# Information on nitrogen output from Kako‘o taro agriculture from Bremer, et al 2018: total N is 0.16 
# (+/- 0.08) g/m^3 with nitrate N 0.006 (+/- 0.014) g/m^3 and ammonia N at 0.006 (+/- 0.006) g/m^3
# these represent an order of magnitude smaller ammonia and nitrate N composition from before

# Nitrogen in FP water column (no measures of organic N):
# summer mean:
# nitrate = 0.66 g/m^3
# ammonium = 0.02 g/m^3

# winter mean:
# nitrate = 0.69 g/m^3
# ammonium = 0.05 g/m^3

# low measured levels of nitrite (0.01 and 0.02 g/^3 in winter and summer, respectively)

# Sediment nitrogen concentrations based on the Briggs, et al paper from 2013 on coastal endmembers

# conversion factor for NH4-N: 1 mg NH4/l = 55.4 umol NH4/l

# In the first 1cm of sediment:
# ammonium (in terrogenous near egret island): 0.54 g/m^3 (~30 uM)
# ammonium (in carbonate sediment in more central part of pond): 0.63 g/m^3 (~35 uM)

# 0.59 g/m^3 average

# organic N: 

# waiting on organic N in FP and sediment, nitrate in sediment.


state <- c(No_st = 0.148, # stream initial organic N [g/m^3]
           Na_st = 0.006, # stream initial ammonium [g/m^3]
           Ni_st = 0.006, # stream initial nitrate [g/m^3]
           No_fp = 0, # fishpond initial organic N [g/m^3]
           Na_fp = 0.035, # fishpond initial ammonium [g/m^3]
           Ni_fp = 0.675, # fishpond initial nitrate [g/m^3]
           No_sd = 0, # fishpond sediment initial organic N [g/m^3]
           Na_sd = 0.59, # fishpond sediment initial ammonium [g/m^3]
           Ni_sd = 0, # fishpond sediment initial nitrate [g/m^3]
           alg = 0,    # fishpond initial algae [g/m^3]
           fish = 0) # fishpond initial fish mass



```






```{r}
fp_out <- ode(y = state, times = t, func = fish_function, parms = pars)
```

```{r}
plot(fp_out) # works if you don't refer to it as a data frame
```

```{r}
fp_df <- as.data.frame(fp_out)
```

```{r}
# Make a nice ggplot with desired content
fp_water <- fp_df %>% 
  select(time, No_fp, Na_fp, Ni_fp) %>% 
  gather('No_fp', 'Na_fp', 'Ni_fp', key = "nitrogen", value = "concentration")
n_fp_plot <- ggplot(data = fp_water, aes(x = time, y = concentration, col=nitrogen)) +
  geom_line()

n_fp_plot
```

```{r}
# Read in water quality data from 2014-2015 in He'eia Fishpond CSV
heeia_data = read_csv('heeia_wq_data_2014_2015.csv')

nitrate_data <- heeia_data %>% 
  select(date, statistic, nitrate) %>% 
  filter(statistic == "Mean" | statistic == "Stdv" | statistic == "N") %>% 
  spread(key = statistic, value = "nitrate") %>% 
  na.omit() %>% 
  rename(nit_mean = Mean, nit_sd = Stdv) %>% 
  mutate(nit_se = nit_sd / sqrt(N)) %>% 
  mutate(date = as.POSIXct(date,format='%m/%d/%Y')) %>% 
  arrange(rev(date))


ammonia_data <- heeia_data %>% 
  select(date, statistic, ammonia) %>% 
  filter(statistic == "Mean" | statistic == "Stdv" | statistic == "N") %>% 
  spread(key = statistic, value = "ammonia") %>% 
  na.omit() %>% 
  rename(amm_mean = Mean, amm_sd = Stdv) %>% 
  mutate(amm_se = amm_sd / sqrt(N)) %>% 
  mutate(date = as.POSIXct(date,format='%m/%d/%Y')) %>% 
  arrange(rev(date))
```

```{r}
nitrate_data_plot <- ggplot(data = nitrate_data, aes(x = date, y = nit_mean)) +
  geom_point(col = 'blue') +
  geom_errorbar(aes(ymin=nit_mean-nit_se, ymax=nit_mean+nit_se), width=.1, col = 'blue') +
  geom_line(linetype = "dashed", col = 'blue') +
  labs(title='Nitrate Concentrations in He‘eia Fishpond 2014-2015', x = 'Sampling Date', y = 'Concentration (mg/L)') +
  theme(axis.text.x= element_text(size = 8), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust = 0.5)) 

nitrate_data_plot
```

```{r}

ammonia_data_plot <- ggplot(data = ammonia_data, aes(x = date, y = amm_mean)) +
  geom_point(col = 'magenta') +
  geom_errorbar(aes(ymin=amm_mean-amm_se, ymax=amm_mean+amm_se), width=.1, col = 'magenta') +
  geom_line(linetype = "dashed", col = 'magenta') +
  labs(title='Ammonia Concentrations in He‘eia Fishpond 2014-2015', x = 'Sampling Date', y = 'Concentration (mg/L)') +
  theme(axis.text.x= element_text(size = 8), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust = 0.5)) 

ammonia_data_plot

```

below is the solve_heeia_logistic Matlab program
```{r}


function [t, N] = solveheeia_logistic(No_in, Na_in, Ni_in, tmax)
    # define physical parameters of ecosystem 
    h_st = 0.5 # average depth of stream [m]
    l_st = 700 # length of interest for He‘eia Stream [m]
    w_st = 15 # approximate width of stream [m]

    A_fp = 360000 # approximate area of fishpond [m^2]
    h_fp = 0.4 # average depth of fishpond water column [m]

    A_sed = 360000 # approximate area of sediment [m^2]
    h_sed = 0.005 # depth of sediment of interest in meters [m]

    # define volumes of compartments - m^3
    V_st = h_st*l_st*w_st # stream
    V_fp = A_fp*h_fp # fishpond water
    V_sed = A_sed*h_sed # fishpond sediment

    # define flow terms - m^3/day
    Q_st = 3500 # mean flow rate of stream as measured in Charles Young Thesis
    # this was measured to be fairly consistent throughout all tides. This
    # is the rate of stream flow among the mangrove bushes by Kako'o and
    # Kamehameha Highway
    
    # previously from thesis: Q_st = 3600 m^3/d
    # 
    # previously from thesis: E_tide = 0.3*144000 # mean daily tidal exchange (m^3/d)
    
    # Spring Flood Tide -> 896,000 m^3/d
    # spring Ebb Tide -> -904,000 m^3/d
    # Neap Flood Tide -> 536,000 m^3/d
    # Neap Ebb Tide -> -482,000 m^3/d
    E_tide_spring = -8300 # difference between spring flood and spring ebb tide m^3/d 
    E_tide_neap = 54000 # difference between neap flood and neap ebb tide m^3/d

    # TSS export from Kako'o marshland 2013 to 2017 was 18.5 mg/L
    
    # difference between each daily tide to get from spring to neap tide
    # values every 8 days with the moon phase change
    daily_tide_diff = (E_tide_neap - E_tide_spring)/8

    # nitrogen chemistry rate constants
    k_oa = 0.05 # conversion of organic N to ammonium N [1/day]
    k_ao = 0.5 # conversion of ammonium N to organic N [1/day]
    k_nit = 3 # nitrification in water column [1/day]
    k_nit_red = 0.1 # reduction of nitrate N to ammonium N [1/day]
    k_av = 0.7 # ammonium to ammonia volatilization rate [1/day]
    k_nit_sed = 1 # nitrification rate in the sediment [1/day]
    k_denit = 0.1 # denitirfication removal from system [1/day]

    # Fishpond water-sediment exchange rate constants
    k_r = 0.1 # resuspension rate [1/d]
    k_s = 0.05 # settling rate [1/d]
    k_b = 0.001 # burial removal rate [1/d] 

    # Temperature currently only influences fish mortality rate
    Temp = 26 # ºC, average fishpond temperature measured 2014-2015

    # fish and algae rates and constants
    a_Na = 0.2 # ratio of nitrogen to Chla in algae [g N/g Chla]
    k_ra = 0.025 # algae respiration rate [1/d]
    k_SN = 0.15 # half-saturation constant for N uptake [gN/m^3]
    k_g20 = 1.5 # algae growth rate constant at 20 degrees C [1/d]
    k_fg = 0.015 # rate of fish growth due to algae consumption [1/d]
    k_fd = 0.0256 + 0.0123*Temp # fish mortality rate [1/d]
    k_ac = 0.0012 # rate of algae consumption by fish [1/d]
    K_alg = 5000 # carrying capacity of algae [g/m^3]

    
    # makes sure that the initial conditions are being included 
    
    # initial nitrogen conditions in fishpond - units g/m^3
    orgST = 0.20 # organic nitrogen in stream
    ammST = 0.06 # ammonia nitrogen in stream
    nitST = 0.04 # nitrate nitrogen in stream
    orgFP = 0.27 # organic nitrogen in fishpond water column
    ammFP = 0.03 # ammonia nitrogen in fishpond water column
    nitFP = 0.67 # nitrate nitrogen in fishpond water column
    orgSED = 0.1 # organic nitrogen in oxic sediment layer
    ammSED = 0.05 # ammonia nitrogen in oxic sediment layer
    nitSED = 0.01 # nitrate nitrogen in oxic sediment layer
    alg = 180 # algae in fishpond water column
    fish = 0.24 # herbivorous fish in fishpond

    # initial nitrogen concentrations in ocean - units g/m^3
    C_No_ocean = 0.001
    C_Na_ocean = 0.04 
    C_Ni_ocean = 0.02

    # solving the system of differential equations
    sol = ode45(@BigModel,[0 tmax],[orgST ammST nitST orgFP... 
        ammFP nitFP orgSED ammSED nitSED alg fish])

    # set time frame for model evaluation
    t = 1:1:tmax

    # evaluate model on the set time frame
    N = deval(sol,t)

function dN = BigModel(t, N)
    
    # start of experimental high tide data is July 23, 2014 which was
    # approaching three days before a fully moon
    
    # Incorporate monthly/seasonal and daily variations in tidal exchange
    if t < 4
        # describe the first few days to 
        Q_tide = E_tide_neap - t*daily_tide_diff
    else
        if mod((t-4),16) == 0
            Q_tide = E_tide_spring
        else if mod((t-4),16) > 0 && mod((t-4),16) < 8
            Q_tide = E_tide_spring + mod((t-4),16)*daily_tide_diff
        else if mod((t-4),16) == 8
            Q_tide = E_tide_neap
        else if mod((t-4),16) > 8 && mod((t-4),16) <= 16
            Q_tide = E_tide_neap - (mod((t-4),16)-8)*daily_tide_diff
        end  
    end

    # Specify temporal variability in He'eia stream flow rate based on mean
    # measurements from 1943-2018
    if t < 68 # End of July, Aug, and Sept
        Q_st = 4160 # m^3/day
    else if t > 67 && t < 99 # Oct
        Q_st = 4890 # m^3/day
    else if t > 98 && t > 129 # Nov
        Q_st = 6850 # m^3/day
    else if t > 128 && t < 160 # Dec
       Q_st = 6600 # m^3/day
   else if t > 159 && t < 191 # Jan
       Q_st = 6360 # m^3/day
    else if t > 190 && t < 219 # Feb
       Q_st = 6360 # m^3/day
    else if t > 218 && t < 250 # March
       Q_st = 8070 # m^3/day
    else if t > 249 && t < 280 # April
       Q_st =  6120 # m^3/day
    else if t > 279 && t < 312 # May
       Q_st =  5630 # m^3/day
    else if t > 311 && t < 342 # June
       Q_st =  3670 # m^3/day 
    else # remainder of July
       Q_st = 4160 # m^3/day
    end
    
    # Specify temporal variability in He'eia stream flow rate based on mean
    # measurements from July 2014-July 2015
    if t < 10 # End of July 2014
        Q_st = 8860 # m^3/day
    else if t > 9 && t < 40 # Aug 2014
        Q_st = 4620 # m^3/day
    else if t > 39 && t < 68 # Sept 2014
        Q_st = 4650 # m^3/day
    else if t > 67 && t < 99 # Oct 2014
        Q_st = 6560 # m^3/day
    else if t > 98 && t > 129 # Nov 2014
        Q_st = 4970 # m^3/day
    else if t > 128 && t < 160 # Dec 2014 
       Q_st = 4580 # m^3/day
   else if t > 159 && t < 191 # Jan 2015 
       Q_st = 4130 # m^3/day
    else if t > 190 && t < 219 # Feb 2015 
       Q_st = 3990 # m^3/day
    else if t > 218 && t < 250 # March 2015 
       Q_st = 3940 # m^3/day
    else if t > 249 && t < 280 # April 2015
       Q_st =  3840 # m^3/day
    else if t > 279 && t < 312 # May 2015
       Q_st =  3600 # m^3/day
    else if t > 311 && t < 342 # June 2015
       Q_st =  4160 # m^3/day 
    else # remainder of July 2015
       Q_st = 3770 # m^3/day
    end
        
    
    # define differential equations
    dN = zeros(length(N),1)
    
    # Stream organic N
    dN(1) = (No_in*Q_st-Q_st*N(1)+(-k_oa*N(1) + k_ao*N(2))*V_st)/V_st
    
    # Stream ammonium
    dN(2) = (Na_in*Q_st-Q_st*N(2)+(k_oa*N(1)-(k_ao+k_nit+k_av)*N(2)+...
            k_nit_red*N(3))*V_st)/V_st
    
    # Stream nitrate    
    dN(3) = (Ni_in*Q_st - Q_st*N(3) + (k_nit*N(2)-k_nit_red*N(3))...
            *V_st)/V_st
    
    # Fishpond water organic N
    dN(4) = ((Q_st*N(1)+((-k_oa-k_s)*N(4)+k_ao*N(5)+k_r*N(7))*V_fp...
            + Q_tide*(C_No_ocean-N(4))))/V_fp
    
    # Fishpond water ammonium    
    dN(5) = (Q_st*N(2) + (k_oa*N(4) - (k_ao+k_nit+k_av+k_s)*N(5)...
            +k_r*N(8))*V_fp+Q_tide*(C_Na_ocean-N(5))-((a_Na*k_g20*...
            ((N(5)+N(6))/(k_SN+N(5)+N(6)))+a_Na*k_ra)*N(10)))/V_fp
    
    # Fishpond water nitrate    
    dN(6) = (Q_st*N(3) + (k_nit*N(5)-k_s*N(6)+k_r*N(9))*V_fp + ...
            Q_tide*(C_Ni_ocean-N(6))-((a_Na*k_g20*((N(5)+N(6))/...
            (k_SN+N(5)+N(6))) + a_Na*k_ra)*N(10)))/V_fp
    
    # Sediment organic N    
    dN(7) = ((k_s*N(4)-(k_oa+k_b+k_r)*N(7) + k_ao*N(8))*V_sed)/V_sed
    
    # Sediment ammonium
    dN(8) = ((k_s*N(5) + k_oa*N(7)-(k_ao+k_nit_sed+k_r+k_b)*N(8)...
            + k_nit_red*N(9))*V_sed)/V_sed
    
    # Sediment nitrate    
    dN(9) = ((k_s*N(6)+k_nit_sed*N(8)-(k_denit+k_nit_red+k_r+...
            k_b)*N(9))*V_sed)/V_sed
    
    # Algae density
    dN(10) = (((a_Na*k_g20*((N(5)+N(6))/(k_SN+N(5)+N(6)))-k_ra...
            -((Q_st-Q_tide)/V_fp)))*N(10)*(1-N(10)/K_alg)-k_ac...
            *N(11)*N(10))
    
    # Fish density
    
    # When algae density drops below a critical level, fish 
    # growth declines and fish begin to die off until algae 
    # density increases again in response to predator decline
    if N(10) < 500 
       dN(11) = -k_fd*N(11)
    else 
       dN(11) = (k_fg*N(10)-k_fd)*N(11) 
    end 
end
end

```

